---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - temper.io
  resources:
  - crontrials
  - trials
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temper.io
  resources:
  - crontrials/finalizers
  - trials/finalizers
  verbs:
  - update
- apiGroups:
  - temper.io
  resources:
  - crontrials/status
  - trials/status
  verbs:
  - get
  - patch
  - update
