apiVersion: temper.io/v1alpha1
kind: CronTrial
metadata:
  labels:
    app.kubernetes.io/name: temper
    app.kubernetes.io/managed-by: kustomize
  name: crontrial-sample
spec:
  # TODO(user): Add fields here
