apiVersion: temper.io/v1alpha1
kind: Trial
metadata:
  labels:
    app.kubernetes.io/name: temper
    app.kubernetes.io/managed-by: kustomize
  name: pod-kill-sample
spec:
  target:
    kind: Deployment
    name: demo-app
  scenarios:
    - type: pod-kill
      duration: 30s
      podKill:
        count: 1
