//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlertSource) DeepCopyInto(out *AlertSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlertSource.
func (in *AlertSource) DeepCopy() *AlertSource {
	if in == nil {
		return nil
	}
	out := new(AlertSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrial) DeepCopyInto(out *CronTrial) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrial.
func (in *CronTrial) DeepCopy() *CronTrial {
	if in == nil {
		return nil
	}
	out := new(CronTrial)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronTrial) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrialHistory) DeepCopyInto(out *CronTrialHistory) {
	*out = *in
	if in.LastHaltReason != nil {
		in, out := &in.LastHaltReason, &out.LastHaltReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrialHistory.
func (in *CronTrialHistory) DeepCopy() *CronTrialHistory {
	if in == nil {
		return nil
	}
	out := new(CronTrialHistory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrialList) DeepCopyInto(out *CronTrialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CronTrial, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrialList.
func (in *CronTrialList) DeepCopy() *CronTrialList {
	if in == nil {
		return nil
	}
	out := new(CronTrialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CronTrialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrialRun) DeepCopyInto(out *CronTrialRun) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrialRun.
func (in *CronTrialRun) DeepCopy() *CronTrialRun {
	if in == nil {
		return nil
	}
	out := new(CronTrialRun)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrialSpec) DeepCopyInto(out *CronTrialSpec) {
	*out = *in
	if in.Safeguards != nil {
		in, out := &in.Safeguards, &out.Safeguards
		*out = new(Safeguards)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrialSpec.
func (in *CronTrialSpec) DeepCopy() *CronTrialSpec {
	if in == nil {
		return nil
	}
	out := new(CronTrialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CronTrialStatus) DeepCopyInto(out *CronTrialStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ActiveScenario != nil {
		in, out := &in.ActiveScenario, &out.ActiveScenario
		*out = new(string)
		**out = **in
	}
	if in.CurrentRun != nil {
		in, out := &in.CurrentRun, &out.CurrentRun
		*out = new(CronTrialRun)
		(*in).DeepCopyInto(*out)
	}
	in.History.DeepCopyInto(&out.History)
	if in.ActiveTrialName != nil {
		in, out := &in.ActiveTrialName, &out.ActiveTrialName
		*out = new(string)
		**out = **in
	}
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CronTrialStatus.
func (in *CronTrialStatus) DeepCopy() *CronTrialStatus {
	if in == nil {
		return nil
	}
	out := new(CronTrialStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Execution) DeepCopyInto(out *Execution) {
	*out = *in
	if in.PauseBetween != nil {
		in, out := &in.PauseBetween, &out.PauseBetween
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Execution.
func (in *Execution) DeepCopy() *Execution {
	if in == nil {
		return nil
	}
	out := new(Execution)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Finding) DeepCopyInto(out *Finding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Finding.
func (in *Finding) DeepCopy() *Finding {
	if in == nil {
		return nil
	}
	out := new(Finding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRecoveryProbe) DeepCopyInto(out *HTTPRecoveryProbe) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRecoveryProbe.
func (in *HTTPRecoveryProbe) DeepCopy() *HTTPRecoveryProbe {
	if in == nil {
		return nil
	}
	out := new(HTTPRecoveryProbe)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsSource) DeepCopyInto(out *MetricsSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsSource.
func (in *MetricsSource) DeepCopy() *MetricsSource {
	if in == nil {
		return nil
	}
	out := new(MetricsSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeDrainConfig) DeepCopyInto(out *NodeDrainConfig) {
	*out = *in
	if in.EvictionTimeout != nil {
		in, out := &in.EvictionTimeout, &out.EvictionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeDrainConfig.
func (in *NodeDrainConfig) DeepCopy() *NodeDrainConfig {
	if in == nil {
		return nil
	}
	out := new(NodeDrainConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PodKillConfig) DeepCopyInto(out *PodKillConfig) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PodKillConfig.
func (in *PodKillConfig) DeepCopy() *PodKillConfig {
	if in == nil {
		return nil
	}
	out := new(PodKillConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecoverySpec) DeepCopyInto(out *RecoverySpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPRecoveryProbe)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecoverySpec.
func (in *RecoverySpec) DeepCopy() *RecoverySpec {
	if in == nil {
		return nil
	}
	out := new(RecoverySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOProtection) DeepCopyInto(out *SLOProtection) {
	*out = *in
	if in.Threshold != nil {
		in, out := &in.Threshold, &out.Threshold
		*out = new(string)
		**out = **in
	}
	if in.Queries != nil {
		in, out := &in.Queries, &out.Queries
		*out = make([]SLOQuery, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOProtection.
func (in *SLOProtection) DeepCopy() *SLOProtection {
	if in == nil {
		return nil
	}
	out := new(SLOProtection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SLOQuery) DeepCopyInto(out *SLOQuery) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SLOQuery.
func (in *SLOQuery) DeepCopy() *SLOQuery {
	if in == nil {
		return nil
	}
	out := new(SLOQuery)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Safeguards) DeepCopyInto(out *Safeguards) {
	*out = *in
	if in.MaxUnavailable != nil {
		in, out := &in.MaxUnavailable, &out.MaxUnavailable
		*out = new(int32)
		**out = **in
	}
	if in.MinReplicasAvailable != nil {
		in, out := &in.MinReplicasAvailable, &out.MinReplicasAvailable
		*out = new(int32)
		**out = **in
	}
	if in.AlertSource != nil {
		in, out := &in.AlertSource, &out.AlertSource
		*out = new(AlertSource)
		**out = **in
	}
	if in.HaltOnAlertLabels != nil {
		in, out := &in.HaltOnAlertLabels, &out.HaltOnAlertLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MetricsSource != nil {
		in, out := &in.MetricsSource, &out.MetricsSource
		*out = new(MetricsSource)
		**out = **in
	}
	if in.SLOProtection != nil {
		in, out := &in.SLOProtection, &out.SLOProtection
		*out = new(SLOProtection)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Safeguards.
func (in *Safeguards) DeepCopy() *Safeguards {
	if in == nil {
		return nil
	}
	out := new(Safeguards)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Scenario) DeepCopyInto(out *Scenario) {
	*out = *in
	out.Duration = in.Duration
	if in.PodKill != nil {
		in, out := &in.PodKill, &out.PodKill
		*out = new(PodKillConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeDrain != nil {
		in, out := &in.NodeDrain, &out.NodeDrain
		*out = new(NodeDrainConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.SpotReclaim != nil {
		in, out := &in.SpotReclaim, &out.SpotReclaim
		*out = new(SpotReclaimConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Scenario.
func (in *Scenario) DeepCopy() *Scenario {
	if in == nil {
		return nil
	}
	out := new(Scenario)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScenarioResult) DeepCopyInto(out *ScenarioResult) {
	*out = *in
	in.InjectedAt.DeepCopyInto(&out.InjectedAt)
	if in.RecoveredAt != nil {
		in, out := &in.RecoveredAt, &out.RecoveredAt
		*out = (*in).DeepCopy()
	}
	if in.Findings != nil {
		in, out := &in.Findings, &out.Findings
		*out = make([]Finding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScenarioResult.
func (in *ScenarioResult) DeepCopy() *ScenarioResult {
	if in == nil {
		return nil
	}
	out := new(ScenarioResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SpotReclaimConfig) DeepCopyInto(out *SpotReclaimConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SpotReclaimConfig.
func (in *SpotReclaimConfig) DeepCopy() *SpotReclaimConfig {
	if in == nil {
		return nil
	}
	out := new(SpotReclaimConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Target) DeepCopyInto(out *Target) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Target.
func (in *Target) DeepCopy() *Target {
	if in == nil {
		return nil
	}
	out := new(Target)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Trial) DeepCopyInto(out *Trial) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Trial.
func (in *Trial) DeepCopy() *Trial {
	if in == nil {
		return nil
	}
	out := new(Trial)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Trial) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialList) DeepCopyInto(out *TrialList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Trial, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialList.
func (in *TrialList) DeepCopy() *TrialList {
	if in == nil {
		return nil
	}
	out := new(TrialList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TrialList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialMetrics) DeepCopyInto(out *TrialMetrics) {
	*out = *in
	if in.MeanRecoveryTime != nil {
		in, out := &in.MeanRecoveryTime, &out.MeanRecoveryTime
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialMetrics.
func (in *TrialMetrics) DeepCopy() *TrialMetrics {
	if in == nil {
		return nil
	}
	out := new(TrialMetrics)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialSpec) DeepCopyInto(out *TrialSpec) {
	*out = *in
	in.Target.DeepCopyInto(&out.Target)
	if in.Scenarios != nil {
		in, out := &in.Scenarios, &out.Scenarios
		*out = make([]Scenario, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(Execution)
		(*in).DeepCopyInto(*out)
	}
	if in.Recovery != nil {
		in, out := &in.Recovery, &out.Recovery
		*out = new(RecoverySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialSpec.
func (in *TrialSpec) DeepCopy() *TrialSpec {
	if in == nil {
		return nil
	}
	out := new(TrialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrialStatus) DeepCopyInto(out *TrialStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(TrialMetrics)
		(*in).DeepCopyInto(*out)
	}
	if in.InjectedAt != nil {
		in, out := &in.InjectedAt, &out.InjectedAt
		*out = (*in).DeepCopy()
	}
	if in.RecoveredAt != nil {
		in, out := &in.RecoveredAt, &out.RecoveredAt
		*out = (*in).DeepCopy()
	}
	if in.ScenarioResults != nil {
		in, out := &in.ScenarioResults, &out.ScenarioResults
		*out = make([]ScenarioResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.HaltReason != nil {
		in, out := &in.HaltReason, &out.HaltReason
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrialStatus.
func (in *TrialStatus) DeepCopy() *TrialStatus {
	if in == nil {
		return nil
	}
	out := new(TrialStatus)
	in.DeepCopyInto(out)
	return out
}
